### ISSUE TITLE
Properly configure netlify to deal with React app

### ISSUE THREAD

**Issue by danillouz** [radient/editor-client#7]

**Comment by dinostheo** [comment]
I think that you need a `netlify.toml` in your root directory.

```toml
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
```
